# Generated by Django 5.1.6 on 2026-06-05 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoAlacena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('calorias', models.IntegerField(default=0)),
                ('proteina', models.FloatField(default=0)),
                ('carbos', models.FloatField(default=0)),
                ('grasas', models.FloatField(default=0)),
                ('veces_usado', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alacena', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-veces_usado', '-creado_en'],
            },
        ),
    ]
