# Generated by Django 5.1.6 on 2026-06-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alimentoalacena'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alimentos_gustados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usuario',
            name='alimentos_no_gustados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estatura_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel_actividad',
            field=models.CharField(blank=True, choices=[('sedentario', 'Sedentario (sin ejercicio)'), ('ligero', 'Ligero (1-3 días/sem)'), ('moderado', 'Moderado (3-5 días/sem)'), ('activo', 'Activo (6-7 días/sem)'), ('muy_activo', 'Muy activo (2x/día)')], max_length=12),
        ),
        migrations.AddField(
            model_name='usuario',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('perder', 'Perder peso'), ('mantener', 'Mantener peso'), ('ganar', 'Ganar músculo')], max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='onboarding_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='peso_inicial_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='peso_objetivo_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='restricciones_dieta',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='velocidad_objetivo',
            field=models.CharField(blank=True, choices=[('suave', 'Suave (~0.25 kg/sem)'), ('moderado', 'Moderado (~0.5 kg/sem)'), ('agresivo', 'Agresivo (~1 kg/sem)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='meta_calorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='meta_carbos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='meta_grasas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='meta_proteina',
            field=models.IntegerField(default=0),
        ),
    ]
