# Generated by Django 5.1.6 on 2026-06-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sesionchat_mensajechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciolog',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
