# Generated by Django 5.1.6 on 2026-06-20 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ejerciciolog_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('musculo', models.CharField(default='Personalizado', max_length=100)),
                ('series', models.IntegerField(default=3)),
                ('reps', models.CharField(default='10', max_length=50)),
                ('peso', models.CharField(default='—', max_length=50)),
                ('color', models.CharField(default='#4ade80', max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_personalizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RutinaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('rutina_id', models.CharField(default='A', max_length=1)),
                ('emoji', models.CharField(default='💪', max_length=10)),
                ('ejercicios', models.JSONField(blank=True, default=list)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_dia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_semana'],
                'unique_together': {('usuario', 'dia_semana')},
            },
        ),
    ]
