# Generated by Django 5.1.6 on 2026-08-14 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_ml', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_agua', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de agua',
                'verbose_name_plural': 'Registros de agua',
                'ordering': ['-creado_en'],
            },
        ),
    ]
