# Generated by Django 5.1.6 on 2026-08-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_registroagua'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciolog',
            name='musculo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
