# Generated by Django 5.1.6 on 2026-09-23 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_doble_entreno'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40)),
                ('nivel', models.PositiveSmallIntegerField(default=0)),
                ('desbloqueado_en', models.DateTimeField()),
                ('visto', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'clave'), name='logro_unico_por_usuario')],
            },
        ),
    ]
