# Generated by Django 5.1.6 on 2026-09-24 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_logros'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comidas', models.JSONField(default=list)),
                ('consejo', models.TextField(blank=True)),
                ('generaciones', models.PositiveSmallIntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'fecha'), name='plan_unico_por_dia')],
            },
        ),
    ]
