# Generated by Django 5.1.6 on 2026-09-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_plan_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alergias',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
