# Generated by Django 5.1.6 on 2026-09-24 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alergias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='slots_enviados',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='slots_fecha',
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='ultima_notif',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ajustes_notif',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='NotificacionEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('cuerpo', models.CharField(max_length=300)),
                ('enviada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enviada'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'clave'), name='notificacion_unica')],
            },
        ),
    ]
