# Generated by Django 5.1.6 on 2026-09-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciopersonalizado',
            name='custom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='biblioteca_creada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ejerciciopersonalizado',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
