# Generated by Django 5.1.6 on 2026-09-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_biblioteca_ejercicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajechat',
            name='acciones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
