# Generated by Django 5.1.6 on 2026-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_metas_minimo_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='metas_manuales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='peso_metas_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
