# Generated by Django 5.1.6 on 2026-09-25 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_metas_por_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='factor_gasto',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='AjusteGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ingesta_media', models.IntegerField()),
                ('cambio_kg_semana', models.FloatField()),
                ('gasto_formula', models.IntegerField()),
                ('gasto_real', models.IntegerField()),
                ('factor', models.FloatField()),
                ('calorias_antes', models.IntegerField()),
                ('calorias_despues', models.IntegerField()),
                ('dias_comida', models.IntegerField()),
                ('pesajes', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_gasto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'fecha'), name='ajuste_gasto_unico_por_dia')],
            },
        ),
    ]
