# Generated by Django 5.1.6 on 2026-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_gasto_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciolog',
            name='series_detalle',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
