# Generated by Django 5.1.6 on 2026-10-05 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def congelar_sesiones(apps, schema_editor):
    """Las sesiones ya guardadas quedan con la rutina como está hoy: es la mejor
    copia disponible y desde aquí ya no cambia aunque se edite la rutina."""
    SesionGym = apps.get_model('api', 'SesionGym')
    sesiones = list(SesionGym.objects.filter(rutina_ref__isnull=False).select_related('rutina_ref'))
    for s in sesiones:
        r = s.rutina_ref
        s.rutina_snapshot = {'nombre': r.nombre, 'emoji': r.emoji, 'color': r.color, 'ejercicios': r.ejercicios}
    SesionGym.objects.bulk_update(sesiones, ['rutina_snapshot'], batch_size=200)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_uid_ejercicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesiongym',
            name='rutina_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CambioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField()),
                ('semana', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_plan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['desde'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'desde'), name='un_plan_por_fecha')],
            },
        ),
        migrations.RunPython(congelar_sesiones, migrations.RunPython.noop),
    ]
